# Evaluate the same selection files as the build without fetching or adding targets.
include("${CMAKE_CURRENT_LIST_DIR}/extension_platform.cmake")

function(discovery_json_string OUTPUT VALUE)
    string(REPLACE "\\" "\\\\" VALUE "${VALUE}")
    string(REPLACE "\"" "\\\"" VALUE "${VALUE}")
    string(REPLACE "\n" "\\n" VALUE "${VALUE}")
    string(REPLACE "\r" "\\r" VALUE "${VALUE}")
    string(REPLACE "\t" "\\t" VALUE "${VALUE}")
    set(${OUTPUT} "\"${VALUE}\"" PARENT_SCOPE)
endfunction()

function(discovery_append_json PROPERTY VALUE)
    get_property(JSON GLOBAL PROPERTY "${PROPERTY}")
    if(NOT "${JSON}" STREQUAL "")
        string(APPEND JSON ",\n")
    endif()
    string(APPEND JSON "${VALUE}")
    set_property(GLOBAL PROPERTY "${PROPERTY}" "${JSON}")
endfunction()

function(duckdb_extension_statically_link)
endfunction()

function(duckdb_extension_load NAME)
    string(TOLOWER "${NAME}" NAME)
    get_property(NAMES GLOBAL PROPERTY DISCOVERY_EXTENSION_NAMES)
    if(NAME IN_LIST NAMES OR NAME IN_LIST SKIP_EXTENSIONS)
        return()
    endif()
    set_property(GLOBAL APPEND PROPERTY DISCOVERY_EXTENSION_NAMES "${NAME}")
    set(options DONT_BUILD LOAD_TESTS APPLY_PATCHES)
    set(oneValueArgs SOURCE_DIR INCLUDE_DIR TEST_DIR GIT_URL GIT_TAG SUBMODULES EXTENSION_VERSION LINKED_LIBS)
    cmake_parse_arguments(PARSE_ARGV 1 EXT "${options}" "${oneValueArgs}" "")
    if("DONT_LINK" IN_LIST EXT_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "DONT_LINK was removed; use STATICALLY_LINK_EXTENSIONS to request linking")
    endif()
    if(EXT_DONT_BUILD)
        return()
    endif()
    if(EXT_SOURCE_DIR AND NOT EXT_GIT_URL)
        get_filename_component(SOURCE_DIR "${EXT_SOURCE_DIR}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        discovery_json_string(SOURCE_DIR "${SOURCE_DIR}")
        discovery_append_json(DISCOVERY_LOCAL_DIRS "${SOURCE_DIR}")
    endif()
    if(NOT EXT_GIT_URL)
        return()
    endif()
    if(NOT EXT_GIT_TAG)
        message(FATAL_ERROR "Git URL specified but no valid GIT_TAG was found for ${NAME} extension")
    endif()
    discovery_json_string(NAME "${NAME}")
    discovery_json_string(URL "${EXT_GIT_URL}")
    discovery_json_string(TAG "${EXT_GIT_TAG}")
    set(SUBMODULES "")
    foreach(SUBMODULE IN LISTS EXT_SUBMODULES)
        discovery_json_string(SUBMODULE "${SUBMODULE}")
        list(APPEND SUBMODULES "${SUBMODULE}")
    endforeach()
    string(JOIN ", " SUBMODULES ${SUBMODULES})
    set(PATCHES false)
    if(EXT_APPLY_PATCHES)
        set(PATCHES true)
    endif()
    discovery_append_json(DISCOVERY_RECORDS
        "{\"name\": ${NAME}, \"git_url\": ${URL}, \"git_tag\": ${TAG}, \"submodules\": [${SUBMODULES}], \"apply_patches\": ${PATCHES}}")
endfunction()

include("${CMAKE_CURRENT_LIST_DIR}/extension_selection.cmake")
get_property(RECORDS GLOBAL PROPERTY DISCOVERY_RECORDS)
get_property(LOCAL_DIRS GLOBAL PROPERTY DISCOVERY_LOCAL_DIRS)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/extensions.json"
    "{\"extensions\": [${RECORDS}], \"local_manifest_dirs\": [${LOCAL_DIRS}]}\n")
